#!/usr/bin/env bash
# displays fizz for %3 =0, buzz for %5=0 , fizzbuzz for %3 & %5 =0.

COUNTER=1
while [ $COUNTER -lt 101 ]
do
    if [ $((COUNTER%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((COUNTER%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((COUNTER%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$COUNTER"
    fi
    let COUNTER+=1
done
